name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v5

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      # This enables task distribution via Nx Cloud
      - run: pnpm dlx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      - run: pnpm install --frozen-lockfile

      - run: pnpm nx record -- pnpm nx format:check --base="remotes/origin/main"
      - run: pnpm nx run-many -t lint test build typecheck e2e-ci
      # Nx Cloud recommends fixes for failures
      - run: pnpm nx fix-ci
        if: always()
